### ISSUE TITLE
[BUG] Analysis looks exactly the same with and without known libs

### ISSUE THREAD

**Issue by jmle** [konveyor/analyzer-lsp#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

0.3.0-alpha.5

### Priority

Critical

### Current Behavior

When analyzing the `sample.daytrader7` app with both _Application and internal dependencies only_ and _Application and all dependencies, including known Open Source libraries_, the exact same number of issues appear.

### Expected Behavior

Both scopes of analysis should be different, with the _Application and internal dependencies only_ analysing only the given application and any potential internal dependencies, and _Application and all dependencies, including known Open Source libraries_ showing those issues and also issues related to known libraries.

### How Reproducible

Always (Default)

### Steps To Reproduce

1. Using the given environment, analyze the [sample.daytrader7 app (master branch)](https://github.com/WASdev/sample.daytrader7), both times with _Source + dependencies_ mode, but the first time with _Application and internal dependencies only_, and then in a new analysis, with _Application and all dependencies, including known Open Source libraries_.
2. Notice that both analysis look exactly the same in terms of issues found.

### Environment

```markdown
* Fedora 38
* minikube version: v1.31.2
* Konveyor 0.3.0-alpha.5
* [sample.daytrader7 app (master branch)](https://github.com/WASdev/sample.daytrader7)
* Analysis configuration:
** Source code + dependencies
** eap8, quarkus, openjdk17, azure, cloud-readiness, camel3
** Application and internal dependencies only/Application and all dependencies, including known Open Source libraries
** No custom rules
** No additional advanced options
```

**Comment by jmle** [comment]
To add more information to this, there are two libraries which should be appearing in the analysis (with scope _Application and all dependencies, including known Open Source libraries_) and are not: `org.apache.derby` and `org.apache.taglibs`.

**Comment by pranavgaikwad** [comment]
@jmle Again, I think this is because we weren't able to get dependencies correctly for the app. Can you please confirm this is solved?

**Comment by jmle** [comment]
@pranavgaikwad as of yesterday when I was testing, it still isn't solved

**Comment by jmle** [comment]
Closing this, not reproducible anymore
